# Define the list of CSS files in the correct order
$cssFiles = @(
    'static-uikit/assets/css/base/fonts.css',
    'static-uikit/assets/css/base/tokens.css',
    'static-uikit/assets/css/base/reset.css',
    'static-uikit/assets/css/layout/app.css',
    'static-uikit/assets/css/layout/sidebar.css',
    'static-uikit/assets/css/layout/topbar.css',
    'static-uikit/assets/css/layout/page.css',
    'static-uikit/assets/css/components/cards.css',
    'static-uikit/assets/css/components/buttons.css',
    'static-uikit/assets/css/components/forms.css',
    'static-uikit/assets/css/components/badges.css',
    'static-uikit/assets/css/components/tables.css',
    'static-uikit/assets/css/components/tabs.css',
    'static-uikit/assets/css/components/filters.css',
    'static-uikit/assets/css/components/modals.css',
    'static-uikit/assets/css/pages/dashboard.css',
    'static-uikit/assets/css/pages/subjects.css',
    'static-uikit/assets/css/pages/subject-card.css',
    'static-uikit/assets/css/pages/contract-wizard.css',
    'static-uikit/assets/css/pages/contract-edit.css',
    'static-uikit/assets/css/pages/subject-register.css',
    'static-uikit/assets/css/pages/subject-edit.css',
    'static-uikit/assets/css/pages/brokerage.css',
    'static-uikit/assets/css/pages/trust-management.css',
    'static-uikit/assets/css/pages/requests.css',
    'static-uikit/assets/css/pages/back-office.css',
    'static-uikit/assets/css/pages/archive.css',
    'static-uikit/assets/css/pages/agents.css',
    'static-uikit/assets/css/pages/compliance.css',
    'static-uikit/assets/css/pages/middle-office.css',
    'static-uikit/assets/css/pages/trading.css',
    'static-uikit/assets/css/pages/depository.css',
    'static-uikit/assets/css/pages/document-wizard.css',
    'static-uikit/assets/css/pages/error.css',
    'static-uikit/assets/css/pages/search-results.css',
    'static-uikit/assets/css/responsive.css',
    'static-uikit/assets/css/print.css'
)

$outputPath = 'static-uikit/assets/css/crm-static.bundle.css'

# Create header comment block
$header = @"
/* =============================================================================
   CRM Static Bundle CSS
   Generated by PowerShell Bundle Script
   Concatenates all modular CSS files in dependency order
   Do not edit manually - regenerate using the bundle script
   ============================================================================= */

"@

# Initialize output content
$bundleContent = $header

# Process each CSS file
foreach ($cssFile in $cssFiles) {
    if (Test-Path $cssFile) {
        # Add section marker
        $fileName = Split-Path $cssFile -Leaf
        $bundleContent += "`n/* ===== $fileName ===== */`n"
        
        # Read file content and filter out @import statements
        $fileContent = Get-Content $cssFile -Raw
        
        # Remove @import statements
        $fileContent = $fileContent -replace '@import\s+[^;]+;', ''
        
        # Add file content
        $bundleContent += $fileContent
        $bundleContent += "`n"
        
        Write-Host "✓ Added: $cssFile" -ForegroundColor Green
    } else {
        Write-Host "✗ Missing: $cssFile" -ForegroundColor Red
    }
}

# Write the bundle file
$bundleContent | Set-Content $outputPath -Encoding UTF8

# Verify the output
if (Test-Path $outputPath) {
    $fileSize = (Get-Item $outputPath).Length
    $lineCount = (Get-Content $outputPath | Measure-Object -Line).Lines
    Write-Host "`nBundle created successfully!" -ForegroundColor Green
    Write-Host "Output file: $outputPath"
    Write-Host "File size: $fileSize bytes"
    Write-Host "Total lines: $lineCount"
} else {
    Write-Host "Error: Failed to create bundle file" -ForegroundColor Red
}
