import type { ThemeDefinition, ThemeId } from './themeTypes';

export const themes: Record<ThemeId, ThemeDefinition> = {
  current: {
    id: 'current',
    name: 'Current',
    description: 'Текущий дизайн CRM по умолчанию без визуальных изменений пользовательского сценария.',
    primary: '#2563eb',
    secondary: '#dbeafe',
    background: '#f8fafc',
    surface: '#ffffff',
    sidebar: '#ffffff',
    textPrimary: '#0f172a',
    textSecondary: '#64748b',
    border: '#e2e8f0',
    accent: '#1d4ed8',
    logoVariant: 'full-ru',
    logoTone: 'blue',
  },
  'investica-dark': {
    id: 'investica-dark',
    name: 'Investica Dark',
    description: 'Брендовая тёмная тема Инвестика для сценариев с низкой яркостью окружения.',
    primary: '#242BF5',
    secondary: '#474EFD',
    background: '#050507',
    surface: '#0f1021',
    sidebar: '#0A0B6A',
    textPrimary: '#ffffff',
    textSecondary: '#cbd5e1',
    border: '#1e1f38',
    accent: '#474EFD',
    logoVariant: 'full-ru',
    logoTone: 'white',
  },
  'investica-light': {
    id: 'investica-light',
    name: 'Investica Light',
    description: 'Брендовая светлая тема Инвестика с тёмно-синим сайдбаром и читаемым контентом.',
    primary: '#2C3FB0',
    secondary: '#e0e7ff',
    background: '#f5f7fb',
    surface: '#ffffff',
    sidebar: '#101A5A',
    textPrimary: '#0f172a',
    textSecondary: '#475569',
    border: '#dbe2f0',
    accent: '#3A4FC6',
    logoVariant: 'full-ru',
    logoTone: 'blue',
  },
  'investica-command': {
    id: 'investica-command',
    name: 'Investica Command Center',
    description: 'Операционный режим командного центра для плотной ежедневной работы с потоком задач.',
    primary: '#2f5dff',
    secondary: '#1d2f52',
    background: '#08101d',
    surface: '#121b2b',
    sidebar: '#0b1424',
    textPrimary: '#ecf3ff',
    textSecondary: '#9badc8',
    border: '#2a3a53',
    accent: '#4d78ff',
    logoVariant: 'full-ru',
    logoTone: 'white',
  },
  'investica-private': {
    id: 'investica-private',
    name: 'Investica Private Office',
    description: 'Премиальный private office режим для executive-досье клиентов и спокойной аналитической работы.',
    primary: '#1d3f8f',
    secondary: '#e9edf8',
    background: '#f3f0ea',
    surface: '#f8f5ef',
    sidebar: '#e8e1d4',
    textPrimary: '#1b2433',
    textSecondary: '#5b6577',
    border: '#d7d0c2',
    accent: '#2c4fa6',
    logoVariant: 'full-ru',
    logoTone: 'blue',
  },
};

export const DEFAULT_THEME_ID: ThemeId = 'current';

export const THEME_STORAGE_KEY = 'crm-theme';

export const getThemeById = (themeId: ThemeId) => themes[themeId];

export const isThemeId = (value: string): value is ThemeId => value in themes;
