import type { BadgeVariant } from './Badge';

export const statusBadgeVariantMap: Record<string, BadgeVariant> = {
  'РЕЗИДЕНТ': 'success',
  'НЕ РЕЗИДЕНТ': 'neutral',
  'РЕЗИДЕНТ РФ': 'success',
  'НЕРЕЗИДЕНТ': 'neutral',
  'Резидент РФ': 'success',
  Нерезидент: 'neutral',
  'ПРОЙДЕН': 'success',
  'НА ПРОВЕРКЕ': 'warning',
  'НА ДОРАБОТКЕ': 'orange',
  'ЗАБЛОКИРОВАН': 'danger',
  Пройден: 'success',
  'На проверке': 'warning',
  'На доработке': 'orange',
  Заблокирован: 'danger',
  'ДЕЙСТВУЮЩИЙ': 'success',
  'НЕ ДЕЙСТВУЮЩИЙ': 'neutral',
  'ОЖИДАЕТ': 'warning',
  'ПРИНЯТО': 'info',
  'ОТКЛОНЕНО': 'danger',
  Ожидает: 'warning',
  Принято: 'info',
  Отклонено: 'danger',
  'ДОСТАВЛЕНО': 'purple',
  'НЕ ДОСТАВЛЕНО': 'orange',
};
