import type { BadgeVariant } from './Badge';

export const statusBadgeVariantMap: Record<string, BadgeVariant> = {
  'РЕЗИДЕНТ': 'neutral',
  'НЕ РЕЗИДЕНТ': 'neutral',
  'РЕЗИДЕНТ РФ': 'neutral',
  'НЕРЕЗИДЕНТ': 'neutral',
  'Резидент РФ': 'neutral',
  Нерезидент: 'neutral',
  'ПРОЙДЕН': 'success',
  'НА ПРОВЕРКЕ': 'info',
  'НА ДОРАБОТКЕ': 'warning',
  'ЗАБЛОКИРОВАН': 'danger',
  Пройден: 'success',
  'На проверке': 'info',
  'На доработке': 'warning',
  Заблокирован: 'danger',
  'ДЕЙСТВУЮЩИЙ': 'success',
  'НЕ ДЕЙСТВУЮЩИЙ': 'neutral',
  'ОЖИДАЕТ': 'warning',
  'ПРИНЯТО': 'info',
  'ОТКЛОНЕНО': 'danger',
  Ожидает: 'warning',
  Принято: 'info',
  Отклонено: 'danger',
  'ДОСТАВЛЕНО': 'neutral',
  'НЕ ДОСТАВЛЕНО': 'danger',
  Да: 'success',
  Нет: 'neutral',
  'Юр. лицо': 'neutral',
  'Физ. лицо': 'neutral',
  ИП: 'neutral',
};
